author:
        name: Microsoft

description: Use SQL Server ML Services to build and deploy a machine learning model which recommends actions to maximize the purchase rate of leads targeted by a campaign.

gems:
  - jekyll-redirect-from

cig_text: SQL Server VM on Azure
onp_text: SQL Server On-Premises 
hdi_text: HDInsight Spark

db_name: Campaign_R
folder_name: Campaign

pbix_hdidownload_url: "https://github.com/Microsoft/r-server-campaign-optimization/blob/master/Campaign%20Optimization%20Dashboard%20HDI.pbix"
pbix_sqldownload_url: "https://github.com/Microsoft/r-server-campaign-optimization/blob/master/Campaign%20Optimization%20Dashboard.pbix"
pbix_view_url: "https://pcsadwebapp.azurewebsites.net/Solutions/Byod?solutionId=campaignoptimization"